apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${{ values.appname }}
  labels:
    app: ${{ values.appname }}
    backstage.io/kubernetes-id: ${{ values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-${{ values.appname }}
  template:
    metadata:
      labels:
        app: app-${{ values.appname }}
        backstage.io/kubernetes-id: ${{ values.appname }}
    spec:
      containers:
        - name: app-${{ values.appname }}
          image: paulbouwer/hello-kubernetes:1.10
          env:
            - name: MESSAGE
              value: "Hello from Azure Ninja AKS!"
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${{ values.appname }}
  labels:
    backstage.io/kubernetes-id: ${{ values.appname }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-${{ values.appname }}